global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
  
  # Example job for <name>
  # - job_name: '<name>'
  #   static_configs:
  #     - targets: ['<name>:<port>']