@startuml

package "Technical Storage" {
    class SingleTrace {
        + long Id [Key]
    
        + DateTime StartTimeStamp
        + DateTime EndTimeStamp
        
        + int Protocol [Enum]
        + int TypeOfService [Enum]
    
        + NetworkHost SourceHost
        + int SourcePort
        
        + NetworkHost DestinationHost
        + int Destination
        
        + long ByteCount
        + long PacketCount
    }
    SingleTrace-> NetworkHost
    
    class NetworkHost {
        + long Id [Key]
    
        + IpAddress IpAddress [Unique]
        
        + DateTime LastAccessedDnsName
        + string DnsName [Unique]
        
        + NetworkHost NetworkHost
    }
}

package "Layout Storage" {
    class LayoutPreset {
        + long Id [Key]
        + string Name [Unique]
    }

    class GraphNode {
        + long Id [Key]
        + int LayoutId
        
        + string DisplayName
    }
    GraphNode -> LayoutPreset
    
    class HostNode {
        + long NetworkHostId
        + long? IslandId
    }
    HostNode -* GraphNode
    HostNode --> NetworkHost
    
    class CompressedGroup {
        + long GraphElementId
        + long NetworkHostId
    }
    CompressedGroup -* GraphNode
    CompressedGroup -> NetworkHost
}

@enduml
