version: '3.9'
services:
  fennec:
    build:
      context: ../Packrat
      dockerfile: ../Docker/fennec.Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - "2055:2055/udp"
    environment:
      - ASPNETCORE_ENVIRONMENT=${FENNEC_ENVIRONMENT}
      - FENNEC_STARTUP__ENABLESWAGGER=${FENNEC_SWAGGER}
      - FENNEC_STARTUP__ALLOWCORS=${FENNEC_CORS}
      - FENNEC_SECURITY__ACCESS__USERNAME=${FENNEC_INITIAL_USERNAME}
      - FENNEC_SECURITY__ACCESS__PASSWORD=${FENNEC_INITIAL_PASSWORD}
    volumes:
      - fennec_data:/app/Data
    depends_on:
      - mongo
    networks:
      - netanol-network

  astrapia:
    build:
      context: ../Astrapia
      dockerfile: ../Docker/astrapia.Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    networks:
      - netanol-network

  mongo:
    image: mongo:jammy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - netanol-network
  
  nginx:
    image: nginx:latest
    extra_hosts: [ "host.docker.internal:host-gateway" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    environment:
      - NGINX_FENNEC
      - NGINX_GRAFANA
      - NGINX_ASTRAPIA
    ports:
      - "${NGINX_EXPOSED_ADDRESS}:80:80"
    networks:
      - netanol-network
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/nginx.template.conf
    command: /bin/sh -c "envsubst '$$NGINX_FENNEC,$$NGINX_GRAFANA,$$NGINX_ASTRAPIA' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
  
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SERVER_ROOT_URL=http://$NGINX_EXPOSED_ADDRESS/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - loki
    profiles:
      - prod
    networks:
      - netanol-network
  
  loki:
    image: grafana/loki:master
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - netanol-network
    profiles:
      - prod
  
  replay:
    extra_hosts: [ "host.docker.internal:host-gateway" ]
    build:
      context: ./replay
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    environment:
      - REPLAY_FILE
      - REPLAY_TARGET
      - REPLAY_SPEED
    networks:
      - netanol-network
    profiles:
      - dev
    
volumes:
  postgres_data:
  elasticsearch_data:
  fennec_data:
  grafana_data:
  mongo_data:

networks:
  netanol-network:
    driver: bridge