version: '3.9'
services:
  fennec:
    build:
      context: ../Packrat
      dockerfile: ../Docker/fennec.Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - "2055:2055/udp"
    environment:
      - ASPNETCORE_ENVIRONMENT=${FENNEC_ENVIRONMENT}
      - FENNEC_STARTUP__ENABLESWAGGER=${FENNEC_SWAGGER}
      - FENNEC_STARTUP__ALLOWCORS=${FENNEC_CORS}
      - FENNEC_SECURITY__ACCESS__USERNAME=${FENNEC_INITIAL_USERNAME}
      - FENNEC_SECURITY__ACCESS__PASSWORD=${FENNEC_INITIAL_PASSWORD}
      - FENNEC_SECURITY__JWT__KEY=${FENNEC_JWT_KEY}
    depends_on:
      - postgres
    networks:
      - netanol-network

  astrapia:
    build:
      context: ../Astrapia
      dockerfile: ../Docker/astrapia.Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    depends_on:
      - postgres
      - fennec
    networks:
      - netanol-network

  postgres:
    image: postgres:12
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - netanol-network
  
  nginx:
    image: nginx:latest
    extra_hosts: [ "host.docker.internal:host-gateway" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    environment:
      - NGINX_FENNEC
      - NGINX_GRAFANA
      - NGINX_ASTRAPIA
    ports:
      - "${NGINX_EXPOSED_ADDRESS}:80:80"
    networks:
      - netanol-network
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/nginx.template.conf
    command: /bin/sh -c "envsubst '$$NGINX_FENNEC,$$NGINX_GRAFANA,$$NGINX_ASTRAPIA' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
  
  elasticsearch:
    image: elasticsearch:8.8.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - netanol-network
    profiles:
      - prod
  
  kibana:
    image: kibana:8.8.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - "5601:5601"
    networks:
      - netanol-network
    profiles:
      - prod
  
  replay:
    extra_hosts: [ "host.docker.internal:host-gateway" ]
    build:
      context: ./replay
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    environment:
      - REPLAY_FILE
      - REPLAY_TARGET
      - REPLAY_SPEED
    networks:
      - netanol-network
    profiles:
      - dev
    
volumes:
  postgres_data:
  elasticsearch_data:
    
networks:
  netanol-network:
    driver: bridge