version: '3.9'
services:
  fennec:
    build:
      context: ../TAPAS
      dockerfile: ../Docker/Dockerfile
    ports:
      - "8000:80/tcp"
      - "2055:2055/udp"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - postgres
    networks: 
      - netanol-network
    profiles:
      - dev
      - prod

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - netanol-network
    profiles:
      - dev
      - prod
  
  elasticsearch:
    image: elasticsearch:8.8.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - netanol-network
    profiles:
      - dev
      - prod
  
  kibana:
    image: kibana:8.8.1
    ports:
      - "5601:5601"
    networks:
      - netanol-network
    profiles:
      - dev
      - prod
  
  traffic-replay:
    build:
      context: ./traffic-replay
    environment:
      - TRAFFIC_REPLAY_FILE
    profiles:
      - dev
    
volumes:
  postgres_data:
  elasticsearch_data:
    
networks:
  netanol-network:
    driver: bridge