@startuml

package "Technical Storage" {
    class SingleTrace {
        + long Id 
    
        + DateTime StartTimeStamp
        + DateTime EndTimeStamp
        
        + int Protocol [Enum]
        + int TypeOfService [Enum]
    
        + NetworkHost SourceHost
        + int SourcePort
        
        + NetworkHost DestinationHost
        + int Destination
        
        + long ByteCount
        + long PacketCount
    }
    SingleTrace-> NetworkHost
    
    class NetworkHost {
        + long Id 
    
        + IpAddress IpAddress [Unique]
        
        + DateTime LastAccessedDnsName
        + string DnsName [Unique]
        
        + NetworkHost NetworkHost
    }
}

package "Layout Storage" {
    class Layout {
        + long Id
        + string Name [Unique]
    }

    class GraphNode {
        + long Id
        + int LayoutId
        + string DisplayName
        + bool Hidden
    }
    GraphNode -> Layout
    
    class HostNode {
        + NetworkHost
        + long? IslandGroup
    }
    HostNode -* GraphNode
    HostNode --> NetworkHost
    
    class CompressedGroup {
        + long Id
        + GraphNode
        + NetworkHost
    }
    CompressedGroup -> GraphNode
    CompressedGroup -> NetworkHost
}

@enduml
