name: Astrapia Continuous Integration

on:
  push:
  pull_request:

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Nuxt dependencies
        working-directory: Astrapia
        run: npm install

      - name: Build Nuxt
        working-directory: Astrapia
        run: npm run build