name: Continuous Deployment to C414

on:
  push:

jobs:
  deploy_to_c414:
    runs-on: [ self-hosted, c414-label ]

    steps:        
      - name: Stop Docker Compose Services
        continue-on-error: true
        run: |
          cd ~/netanol/Docker && docker compose down
          
      - name: Remove Old Files
        continue-on-error: true
        run: |
          rm -rf ~/netanol
          
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Copy Code
        run: |
          mkdir ~/netanol && cp -r . ~/netanol

      - name: Run Remote Docker
        run: |
          cd ~/netanol/Docker && 
          docker compose build --no-cache && 
          docker compose --profile prod --env-file .env --env-file c414/docker.env up -d
