name: Fennec Continuous Integration

on:
  push:
  pull_request:

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Restore NuGet packages
        working-directory: Packrat/Fennec.Tests
        run: |
          dotnet restore

      - name: Build solution
        working-directory: Packrat/Fennec.Tests
        run: |
          dotnet build --no-restore

      - name: Run tests
        working-directory: Packrat/Fennec.Tests
        run: |
          dotnet test --no-build --verbosity normal
