name: Fennec Continuous Integration

on:
  push:
  pull_request:

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore NuGet packages
        working-directory: TAPAS/Fennec.Tests
        run: |
          dotnet restore

      - name: Build solution
        working-directory: TAPAS/Fennec.Tests
        run: |
          dotnet build --no-restore

      - name: Run tests
        working-directory: TAPAS/Fennec.Tests
        run: |
          dotnet test --no-build --verbosity normal
