name: Manager Continuous Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Nuxt dependencies
        working-directory: Manager/node_modules
        run: npm install

      - name: Build Nuxt
        working-directory: Manager/.output/
        run: npm run build
