name: Continuous Deployment to Syde

on:
  push:

jobs:
  deploy_to_syde:
    runs-on: ubuntu-latest
    env:
      SYDE_HOST: ${{ secrets.SYDE_HOST }}
      SYDE_USER: ${{ secrets.SYDE_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SYDE_RSA }}
  
      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa $SYDE_HOST >> ~/.ssh/known_hosts
  
      - name: Stop Docker Compose Services
        continue-on-error: true
        run: |
          ssh $SYDE_USER@$SYDE_HOST "cd ~/netanol/Docker && docker compose down"
          
      - name: Remove Old Files
        continue-on-error: true
        run: |
          ssh $SYDE_USER@$SYDE_HOST "rm -rf ~/netanol"
  
      - name: SCP Transfer to User's Home Directory
        run: |
          ssh $SYDE_USER@$SYDE_HOST "mkdir -p ~/netanol"
          scp -r $GITHUB_WORKSPACE/* $SYDE_USER@$SYDE_HOST:~/netanol

      - name: Run Remote Docker
        run: |
          ssh $SYDE_USER@$SYDE_HOST "
          cd ~/netanol/Docker && 
          docker compose build --no-cache && 
          docker compose --profile dev --env-file .env --env-file syde/docker.env up -d"
